"""empty message

Revision ID: f0f0e0163573
Revises: 46fcd4a61c3b
Create Date: 2020-05-16 17:41:05.718510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0f0e0163573'
down_revision = '46fcd4a61c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=32), nullable=False))
    # ### end Alembic commands ###
